[2023-10-17 07:51:15,893] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: currency_btc_rub_every_10_munutes.get_rate_from_api_task scheduled__2023-10-17T07:40:00+00:00 [queued]>
[2023-10-17 07:51:15,908] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: currency_btc_rub_every_10_munutes.get_rate_from_api_task scheduled__2023-10-17T07:40:00+00:00 [queued]>
[2023-10-17 07:51:15,909] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-10-17 07:51:15,910] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2023-10-17 07:51:15,911] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-10-17 07:51:15,930] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): get_rate_from_api_task> on 2023-10-17 07:40:00+00:00
[2023-10-17 07:51:15,937] {standard_task_runner.py:52} INFO - Started process 643 to run task
[2023-10-17 07:51:15,942] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'currency_btc_rub_every_10_munutes', 'get_rate_from_api_task', 'scheduled__2023-10-17T07:40:00+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/hello.py', '--cfg-path', '/tmp/tmpssarjfba', '--error-file', '/tmp/tmpn1e5hq94']
[2023-10-17 07:51:15,943] {standard_task_runner.py:80} INFO - Job 43: Subtask get_rate_from_api_task
[2023-10-17 07:51:16,044] {task_command.py:371} INFO - Running <TaskInstance: currency_btc_rub_every_10_munutes.get_rate_from_api_task scheduled__2023-10-17T07:40:00+00:00 [running]> on host 5ae209acedc4
[2023-10-17 07:51:16,152] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Andrey1309
AIRFLOW_CTX_DAG_ID=currency_btc_rub_every_10_munutes
AIRFLOW_CTX_TASK_ID=get_rate_from_api_task
AIRFLOW_CTX_EXECUTION_DATE=2023-10-17T07:40:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-10-17T07:40:00+00:00
[2023-10-17 07:51:16,154] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: get_rate_from_api() takes 0 positional arguments but 6 were given
[2023-10-17 07:51:16,168] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=currency_btc_rub_every_10_munutes, task_id=get_rate_from_api_task, execution_date=20231017T074000, start_date=20231017T075115, end_date=20231017T075116
[2023-10-17 07:51:16,181] {standard_task_runner.py:97} ERROR - Failed to execute job 43 for task get_rate_from_api_task (get_rate_from_api() takes 0 positional arguments but 6 were given; 643)
[2023-10-17 07:51:16,235] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-10-17 07:51:16,286] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
